#!/bin/sh

if [ ! -d "/data" ]; then
  echo "Please mount a directory to backup with -v /path/to/your/dir:/data"
  exit 1
fi

if [ -z "$BACKUP_BUCKET_NAME" ]; then
  echo "Please set the bucket name"
  exit 1
fi

if [ -z "$BACKUP_NAME" ]; then
  echo "Please set the backup name"
  exit 1
fi

echo "Preparing backup..."

_date=$(date -u +"%Y-%m-%d")
_time=$(date -u +"%T")
_name="s3://${BACKUP_BUCKET_NAME}/${_date}/${BACKUP_NAME}-${_time}.tgz"
/bin/tar -czf - /data | \
  aws s3 cp - \
  "$_name" \
  --storage-class GLACIER

# shellcheck disable=SC2181
if [ $? -eq 0 ]; then
  echo "The backup called $_name has been uploaded"
else
  echo "Backup failed"
fi